[package]
name = "core-mqtt-agent"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
core-mqtt-sys = { path = "core-mqtt-sys" }

[workspace]
members = ["core-mqtt-sys"]